services:
  fastify-5:
    build: .
    container_name: fastify-5
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./app
      - /app/node_modules
    env_file:
      - .env.docker
    networks:
      - dev-network

networks:
  dev-network:
    external: true
